### ISSUE TITLE
ah command not work

### ISSUE THREAD

**Issue by saedsohili** [LegendSound/AuctionHousePE#1]
Hello LegendSound
 
Tnx for your new Auctionhouse plugin.

When i use /ah command not things do and no things show in console and chat

**Comment by LeoBdt** [comment]
the command is /market

**Comment by saedsohili** [comment]
Are you forget set /market in plugin.yml ?

name: AuctionHouse
main: LS\AuctionHouse\Main
api: [3.0.0]
version: 1.0
author: LegendSound

commands:
 ah:
  description: "Open AuctionHouse"
